language: c++

# attempt to install GCC 4.8 when necessary, otherwise we wont have C++11 support
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX=g++-4.8; fi

compiler:
  - clang
  - gcc

script:
    - make test
